[opcache]
opcache.enable=1
; 0 means it will never check for updates. best for prod performance.
; requires restarting php container to see code changes.
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.max_wasted_percentage=10
opcache.save_comments=1
; Disable JIT on ARM64 as it causes php-fpm segfaults (502 Bad Gateway)
; opcache.jit_buffer_size=100M
; opcache.jit=tracing

